version: '2'
services:
  web:
    build: .
    environment:
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
      APP_URL: ${APP_URL}
      ASSETS_PATH: '/usr/src/electron-release-server/releases'
    depends_on:
      - db
    ports:
      - '5000:80'
    entrypoint: ./scripts/wait.sh db:5432 -- npm start
    volumes:
      - ./releases:/usr/src/electron-release-server/releases
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres: 